import type { User, AudioAsset, Pack } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'beatmaker_pro',
    displayName: 'BeatMaker Pro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=beatmaker',
    bio: 'Creating fire beats since 2015',
    followers: 1234,
    following: 567,
    verified: true,
  },
  {
    id: '2',
    username: 'synthwave_kid',
    displayName: 'SynthWave Kid',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=synthwave',
    bio: 'Analog synth enthusiast',
    followers: 890,
    following: 234,
  },
  {
    id: '3',
    username: 'bass_dropper',
    displayName: 'Bass Dropper',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bass',
    bio: 'Sub bass specialist',
    followers: 2345,
    following: 123,
    verified: true,
  },
];

export const mockAssets: AudioAsset[] = [
  {
    id: '1',
    title: 'Heavy Kick Sample',
    description: 'Punchy 808-style kick drum',
    type: 'sample',
    url: '/audio/sample1.wav',
    duration: 0.5,
    bpm: 128,
    key: 'C',
    tags: ['kick', '808', 'trap', 'hip-hop'],
    creator: mockUsers[0],
    createdAt: new Date('2024-01-15'),
    likes: 234,
    downloads: 567,
  },
  {
    id: '2',
    title: 'Melodic House Loop',
    description: 'Uplifting melodic house progression',
    type: 'loop',
    url: '/audio/loop1.wav',
    duration: 8.0,
    bpm: 124,
    key: 'Am',
    tags: ['house', 'melodic', 'loop', 'progressive'],
    creator: mockUsers[1],
    createdAt: new Date('2024-01-20'),
    likes: 456,
    downloads: 789,
  },
  {
    id: '3',
    title: 'Chill MIDI Chord',
    description: 'Smooth jazz chord progression',
    type: 'midi',
    url: '/midi/chord1.mid',
    bpm: 90,
    key: 'Gmaj7',
    tags: ['midi', 'chords', 'jazz', 'chill'],
    creator: mockUsers[1],
    createdAt: new Date('2024-01-22'),
    likes: 123,
    downloads: 234,
  },
  {
    id: '4',
    title: 'Bass Stem',
    description: 'Deep sub bass layer',
    type: 'stem',
    url: '/audio/bass-stem.wav',
    duration: 16.0,
    bpm: 140,
    key: 'F#',
    tags: ['bass', 'stem', 'dnb', 'dubstep'],
    creator: mockUsers[2],
    createdAt: new Date('2024-01-25'),
    likes: 345,
    downloads: 456,
  },
  {
    id: '5',
    title: 'Vintage Synth Preset',
    description: 'Warm analog-style pad preset',
    type: 'preset',
    url: '/presets/synth-pad.fxp',
    tags: ['preset', 'synth', 'pad', 'ambient'],
    creator: mockUsers[1],
    createdAt: new Date('2024-01-28'),
    likes: 567,
    downloads: 678,
  },
  {
    id: '6',
    title: 'Trap Hi-Hat Roll',
    description: 'Fast hi-hat roll pattern',
    type: 'sample',
    url: '/audio/hihat-roll.wav',
    duration: 2.0,
    bpm: 145,
    tags: ['hi-hat', 'trap', 'roll', 'percussion'],
    creator: mockUsers[0],
    createdAt: new Date('2024-02-01'),
    likes: 678,
    downloads: 890,
  },
  {
    id: '7',
    title: 'Ambient Pad Loop',
    description: 'Ethereal ambient texture',
    type: 'loop',
    url: '/audio/ambient-pad.wav',
    duration: 32.0,
    bpm: 80,
    key: 'Dm',
    tags: ['ambient', 'pad', 'texture', 'atmospheric'],
    creator: mockUsers[1],
    createdAt: new Date('2024-02-03'),
    likes: 234,
    downloads: 345,
  },
  {
    id: '8',
    title: 'Funky Bass MIDI',
    description: 'Groovy bass line pattern',
    type: 'midi',
    url: '/midi/bass-groove.mid',
    bpm: 110,
    key: 'E',
    tags: ['midi', 'bass', 'funk', 'groove'],
    creator: mockUsers[2],
    createdAt: new Date('2024-02-05'),
    likes: 456,
    downloads: 567,
  },
];

export const mockPacks: Pack[] = [
  {
    id: '1',
    title: 'Ultimate Trap Kit',
    description: 'Complete collection of trap essentials',
    coverImage: 'https://picsum.photos/seed/trap/400/400',
    assets: [mockAssets[0], mockAssets[5]],
    creator: mockUsers[0],
    createdAt: new Date('2024-01-30'),
    likes: 890,
    downloads: 1234,
    tags: ['trap', 'kit', 'collection', 'drums'],
  },
  {
    id: '2',
    title: 'Melodic House Bundle',
    description: 'Everything you need for melodic house',
    coverImage: 'https://picsum.photos/seed/house/400/400',
    assets: [mockAssets[1], mockAssets[6]],
    creator: mockUsers[1],
    createdAt: new Date('2024-02-10'),
    likes: 567,
    downloads: 789,
    tags: ['house', 'melodic', 'bundle', 'loops'],
  },
  {
    id: '3',
    title: 'Bass Music Pack',
    description: 'Heavy bass sounds and stems',
    coverImage: 'https://picsum.photos/seed/bass/400/400',
    assets: [mockAssets[3], mockAssets[7]],
    creator: mockUsers[2],
    createdAt: new Date('2024-02-15'),
    likes: 1234,
    downloads: 1567,
    tags: ['bass', 'dubstep', 'dnb', 'stems'],
  },
];
